
# Site settings

url: "https://getschomp.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#

baseurl: /getschomp

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Allison Browne"
title: "{ Allison Browne }"
description: "Blog and website of Allison Browne, software engineer."
keywords: "allison, browne, ruby, rails, react"
favicon: "/img/favicon-cogs.ico"

################
# Header layout #
################

black-favicon: "/img/favicon-cog-light.ico"

background-img: "../img/IMG_6071.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 4
start-delay: 200
delete-delay: 3000
lines: # You can add HTML Tags in the Text
  - text: "Imagination is more important than knowledge. For knowledge is limited to all we now know and understand, while imagination embraces the entire world, and all there ever will be to know and understand. ― Einstein"
  - text: Making the simple complicated is commonplace; making the complicated simple, awesomely simple, that's creativity. ― Charles Mingus
  - text: Software is a great combination between artistry and engineering. ― Bill Gates
  - text: Always consider the context. ― Andy Hunt

me-img: "/img/jetpacktocat2.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "https-getschomp-github-io"

syntax-highlight: True

############
# Projects #
############

events:
  - image: "/img/projects/train.png"
    date: "2017"
    title: "Commute Calculator Api"
    description: An api that that makes recommendations to a person or family about where they should live based on public transit proximity and average housing price. The api is built with ruby on rails 5 backed with a neo4j graph database.
    uri: https://github.com/getschomp/commute-calculator-api
  - image: "/img/projects/review-where.png"
    date: "2014"
    title: "Review.where"
    description: A collaborative country review site featuring an admin panel built with highmaps, ruby on rails, postgresql, javascript and JQuery.
    uri: https://review-where.herokuapp.com

# First image of the Projects

projects-img: "/img/projects/default.png"

###########
# Contact #
###########

email: "a.mar.browne@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Allison Browne is a maker. She lives in Cambridge MA, where she works on software projects. In her spare time, Allison likes to read and go outside."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "instagram"
    url: "https://www.instagram.com/allisonbrow/"
  - title: "github"
    url: "https://github.com/getschomp"
  - title: "github"
    url: "https://github.com/abrowne-fiksu"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/browneallison"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Projects: 'projects'
  Contact: 'contact'

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
